### ISSUE TITLE
Long post/page scrolling causes header and menu to dissapear

### ISSUE THREAD

**Issue by MadaManu** [TryGhost/Massively#85]
Hi,

Using this theme in one of my blogs, and I have spotted this issue. On a long page (a lot of content to scroll through) or post, when you scroll back up the top, the header and the menu disappeared. 
I have tried this on the demo as well, and yes it happens there too see this page: [Massively Demo - Apps Integrations](https://massively.ghost.io/apps-integrations/). Scroll down the bottom, then back up, the menu and header is gone as in screenshot below.
![image](https://user-images.githubusercontent.com/3156125/139869289-ca628a43-fcef-4835-8b99-b520199f40fc.png)

**Comment by MadaManu** [comment]
I also tested it with Microsoft Edge Version 95.0.1020.40 (Official build) (64-bit) and Firefox 94.0 (64-bit) but the issue is NOT present using these browsers. So I'm not sure what happens with Chrome.

**Comment by minimaluminium** [comment]
Hey @MadaManu,

I wasn't able to reproduce the issue on my end using Chrome 96.0.4664.55. Would you be able to check if there's any console error when you have the issue?

https://user-images.githubusercontent.com/1418797/143989039-c86f7e13-8ca8-44b0-bfcf-85c784a912f6.mp4

**Comment by safaci2000** [comment]
I'm having the same issue.  You can see the current behavior here:  https://www.gbfest.org.  

This is the only additional code Injection I have.

```css
<style>

.kg-image{
    height: 50%;
    width: 50%;
    float: left;
    padding: 20px;
   }        
    
 .content figure:nth-of-type(_) {
    float: left;
   
  </style>  

<script>
  var search_api_key = 'SECRET';
</script>


```

<img width="1670" alt="Screen Shot 2021-12-19 at 1 24 35 PM" src="https://user-images.githubusercontent.com/62894/146686407-c9c5f6de-a309-4181-b090-5b2088f49dd2.png">
